using Game.General;
using System.Collections.Generic;

namespace Game.Features.Trade
{
    /// <summary>
    /// Represents a specific trade proposal generated by the logic.
    /// Contains information about the country, imported items, and exported items.
    /// </summary>
    public class TradeOfferData
    {
        public CountryId CountryId { get; }
        public IReadOnlyList<ResourceData> Import { get; }
        public IReadOnlyList<ResourceData> Export { get; }

        public TradeOfferData(CountryId countryId, List<ResourceData> import, List<ResourceData> export)
        {
            CountryId = countryId;
            Import = import;
            Export = export;
        }
    }
}
