using Game.General;
using System.Collections.Generic;

namespace Game.Features.Trade
{
    /// <summary>
    /// Represents a specific trade proposal generated by the logic.
    /// Contains information about the country, imported items, and exported items.
    /// </summary>
    public class TradeOfferData
    {
        public CountryId CountryId { get; }
        public IReadOnlyList<ResourceAmount> Import { get; }
        public IReadOnlyList<ResourceAmount> Export { get; }

        public TradeOfferData(CountryId countryId, List<ResourceAmount> import, List<ResourceAmount> export)
        {
            CountryId = countryId;
            Import = import.AsReadOnly();
            Export = export.AsReadOnly();
        }
    }
}
