using Game.General;
using System.Collections.Generic;
using UnityEngine;

namespace Game.Features.Trade
{
    /// <summary>
    /// Represents a specific trade proposal generated by the logic.
    /// Contains information about the country, imported items, and exported items.
    /// </summary>
    public class TradeOfferData
    {
        [SerializeField] private CountryId _countryId;
        [SerializeField] private List<ResourceAmount> _import;
        [SerializeField] private List<ResourceAmount> _export;

        public CountryId CountryId => _countryId;
        public IReadOnlyList<ResourceAmount> Import => _import;
        public IReadOnlyList<ResourceAmount> Export => _export;

        public TradeOfferData(CountryId countryId, List<ResourceAmount> import, List<ResourceAmount> export)
        {
            _countryId = countryId;
            _import = import;
            _export = export;
        }
    }
}